# https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/

version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: apps/stllctn-frontend/Dockerfile.prod
    ports:
      - "3500:80"
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/stllctn-frontend/node_modules
    # command: npm run dev:frontend
    environment:
      NODE_ENV: production
  backend:
    build:
      context: .
      dockerfile: apps/stllctn-backend/Dockerfile.prod
    environment:
      - SQL_HOST=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_DATABASE=postgres
      - NODE_ENV=production
      - RUST_BACKTRACE=1
    ports:
      - "5500:5500"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/stllctn-backend/node_modules
      - ../stellection-data/stellection-data:/data
    depends_on:
      - postgres
    restart: always
    command: [
      # this file must be chmod +x on YOUR COMPUTER
        "./apps/stllctn-backend/scripts/wait-for-it.sh",
        "postgres:5555",
        "--",
        "npm",
        "run",
        "entrypoint:backend"
      ]    
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5555:5555'
    volumes:
      - ../stellection-data/postgres-data:/var/lib/postgresql/data
    command: -p 5555
volumes:
  cache:
    driver: local


