version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3500:3000"
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/frontend/node_modules
#     - /app/backend/node_modules
    command: npm run dev:frontend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SQL_HOST=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_DATABASE=postgres
    ports:
      - "5500:5000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/backend/node_modules
    depends_on:
      - postgres
    restart: always
    command: npm run dev:backend
  # migration:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   command:
  #     [
  #       "./backend/screipts/wait-for-it.sh",
  #       "db:5432",
  #       "--",
  #       "npm",
  #       "run",
  #       "migrate:backend"
  #     ]
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   extra_hosts: 
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     - SQL_HOST=host.docker.internal
  #     - SQL_USER=postgres
  #     - SQL_PASSWORD=password
  #     - SQL_DATABASE=postgres
  #   restart: on-failure:10
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/backend/node_modules
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5555:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend-python:
    build:
      context: .
      dockerfile: backend-python/Dockerfile
    ports:
      - "5501:5000"
    volumes:
      - ./:/app
    restart: always
    command: python3 app.py
volumes:
  cache:
    driver: local
  pgdata:


