version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: apps/stllctn-frontend/Dockerfile.dev
    ports:
      - "3500:3500"
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/stllctn-frontend/node_modules
    command: npm run dev:frontend
  backend:
    build:
      context: .
      dockerfile: apps/stllctn-backend/Dockerfile.dev
    environment:
      - SQL_HOST=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=password
      - SQL_DATABASE=postgres
    ports:
      - "5500:5500"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/apps/stllctn-backend/node_modules
    depends_on:
      - postgres
    restart: always
    entrypoint: ["/bin/sh", "./apps/stllctn-backend/scripts/entrypoint.dev.sh"]
    # command: npm run dev:backend
  # migration:
  #   build:
  #     context: .
  #     dockerfile: apps/stllctn-backend/Dockerfile.dev
  #   command:
  #     [
  #       "./apps/stllctn-backend/scripts/wait-for-it.sh",
  #       "127.0.0.1:5555",
  #       "--",
  #       "npm",
  #       "run",
  #       "migrate"
  #     ]
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   extra_hosts: 
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     - SQL_HOST=host.docker.internal
  #     - SQL_USER=postgres
  #     - SQL_PASSWORD=password
  #     - SQL_DATABASE=postgres
  #   restart: on-failure:10
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #     - /app/stllctn-backend/node_modules
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5555:5555'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5555
  # backend-python:
  #   build:
  #     context: .
  #     dockerfile: backend-python/Dockerfile
  #   ports:
  #     - "5501:5501"
  #   volumes:
  #     - ./:/app
  #   restart: always
  #   command: python3 app.py
volumes:
  cache:
    driver: local
  pgdata:


