openapi: 3.0.0
info:
  description: "This is the documentation for the API endpoints for the [Stellection Cataloger](https://github.com/ckhawks/stellection) project."
  version: 0.0.1
  title: Stellection Cataloger
tags:
  - name: star
    description: An item — the smallest atomic level
  - name: cluster
    description: A collection of stars
paths:
  /stars:
    post:
      tags:
        - star
      summary: Add a new star
      description: ""
      operationId: addStar
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  starid:
                    type: array
                    items:
                      type: integer
                      format: int64
        "405":
          description: Invalid input
    put:
      tags:
        - star
      summary: Update an existing star
      description: ""
      operationId: updateStar
      requestBody:
        $ref: "#/components/requestBodies/Star"
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
    get:
      tags:
        - star
      summary: Retrieve all stars
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                items:
                  type: array
                  items:
                    type: object
  /stars/{starId}:
    get:
      tags:
        - star
      summary: Retrieve a star
      operationId: getStar
      parameters:
        - name: starId
          in: path
          description: ID of star to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Star"
        "404":
          description: Star not found
        "405":
          description: Invalid input
    delete:
      tags:
         - star
      summary: Delete a star
      operationId: deleteStar
      parameters:
        - name: api_key
          in: header
          required: false
          schema:
            type: string
        - name: starId
          in: path
          description: ID of star to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Star"
        "404":
          description: Star not found
        "405":
          description: Invalid input
  /clusters:
    get:
      summary: Retrieve all clusters
      operationId: getClusters
      tags:
        - cluster
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: "#/components/schemas/Cluster"
externalDocs:
  description: Find out more about Stellaric
  url: http://stellaric.pw
servers:
  - url: http://127.0.0.1:5000/
  - url: https://api.stlr.cx/v1/
components:
  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/User"
      description: List of user object
      required: true
    Star:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Star"
      description: Star object that needs to be added to the store
      required: true
  schemas:
    Star:
      type: object
      required:
        - path
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        path:
          type: string
      xml:
        name: Pet
    Cluster:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Cluster
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
      xml:
        name: User
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string