name: Deploy to Unraid
on:
  workflow_dispatch:
jobs:

  pull-and-deploy:
    name: Pull and Deploy
    environment: Prod-Unraid
    runs-on: ubuntu-latest
    steps:
    - name: ssh that shit
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.UNRAID_SSH_HOST }}
        username: ${{ secrets.UNRAID_SSH_USERNAME }}
        key: ${{ secrets.UNRAID_SSH_KEY }}
        passphrase: ${{ secrets.UNRAID_SSH_PASSPHRASE }}
        # password: ${{ secrets.UNRAID_SSH_PASSWORD }}
        # key: ${{ secrets.UNRAID_SSH_KEY }}
        port: ${{ secrets.UNRAID_SSH_PORT }}
        script: |
          cd /mnt/user/appdata/stellection
          git pull
          docker compose down
          docker compose up --build -d
