name: Deploy to Unraid
on:
  workflow_dispatch:
jobs:

  build:
    name: Build
    environment: Prod-Unraid
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.UNRAID_SSH_HOST }}
        username: ${{ secrets.UNRAID_SSH_USERNAME }}
        password: ${{ secrets.UNRAID_SSH_PASSWORD }}
        # key: ${{ secrets.UNRAID_SSH_KEY }}
        port: ${{ secrets.UNRAID_SSH_PORT }}
        script: |
          whoami
          ls -al
